name: validate-pr
on:
  pull_request:
    paths:
      - "**.ts"
jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn compile && yarn test
